version: '2'

services:
  phpfpm:
    image: christhomas/hello-php:v4-phpfpm
    build:
      context: .
      dockerfile: ./docker/Dockerfile.phpfpm
    volumes:
      - ./sock:/sock
      - ./www:/www/

  nginx:
    image: christhomas/hello-php:v4-nginx
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - 8080:80
    volumes:
      - ./sock:/sock
      - ./www/index.php:/www/index.php